// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC73BmcL9Xkd0xZzEhTHf5wgZCiaFv8uWo',
    appId: '1:748986146550:web:5994e299903bed542d96d7',
    messagingSenderId: '748986146550',
    projectId: 'gym-bros-tasks',
    authDomain: 'gym-bros-tasks.firebaseapp.com',
    storageBucket: 'gym-bros-tasks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYccWeFpJqMbNxez74mwcGIr2SYqLHG8Y',
    appId: '1:748986146550:android:fd0ce458b8003c602d96d7',
    messagingSenderId: '748986146550',
    projectId: 'gym-bros-tasks',
    storageBucket: 'gym-bros-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvrKXdQG_B6j8Q8-T7o9Wmf8woy9ZAjw',
    appId: '1:748986146550:ios:abbe069417afa1852d96d7',
    messagingSenderId: '748986146550',
    projectId: 'gym-bros-tasks',
    storageBucket: 'gym-bros-tasks.appspot.com',
    iosBundleId: 'com.example.gymBrosTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTvrKXdQG_B6j8Q8-T7o9Wmf8woy9ZAjw',
    appId: '1:748986146550:ios:abbe069417afa1852d96d7',
    messagingSenderId: '748986146550',
    projectId: 'gym-bros-tasks',
    storageBucket: 'gym-bros-tasks.appspot.com',
    iosBundleId: 'com.example.gymBrosTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC73BmcL9Xkd0xZzEhTHf5wgZCiaFv8uWo',
    appId: '1:748986146550:web:9a3370c6b6b221522d96d7',
    messagingSenderId: '748986146550',
    projectId: 'gym-bros-tasks',
    authDomain: 'gym-bros-tasks.firebaseapp.com',
    storageBucket: 'gym-bros-tasks.appspot.com',
  );
}
